$AppPath = "$PSScriptRoot\HandsOnAzureServiceFabricContainer"
Copy-ServiceFabricApplicationPackage -ApplicationPackagePath $AppPath -ApplicationPackagePathInImageStore HandsOnAzureServiceFabricContainer
Register-ServiceFabricApplicationType HandsOnAzureServiceFabricContainer
New-ServiceFabricApplication fabric:/HandsOnAzureServiceFabricContainer HandsOnAzureServiceFabricContainerType 1.0.0